USE [master]
GO

/****** Object:  Database [aifmda]    Script Date: 7/10/2018 4:52:08 PM ******/
CREATE DATABASE [aifmda]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'aifmda', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.JACKSON\MSSQL\DATA\aifmda.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'aifmda_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.JACKSON\MSSQL\DATA\aifmda_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [aifmda] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [aifmda].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [aifmda] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [aifmda] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [aifmda] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [aifmda] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [aifmda] SET ARITHABORT OFF 
GO

ALTER DATABASE [aifmda] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [aifmda] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [aifmda] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [aifmda] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [aifmda] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [aifmda] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [aifmda] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [aifmda] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [aifmda] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [aifmda] SET  DISABLE_BROKER 
GO

ALTER DATABASE [aifmda] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [aifmda] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [aifmda] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [aifmda] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [aifmda] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [aifmda] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [aifmda] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [aifmda] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [aifmda] SET  MULTI_USER 
GO

ALTER DATABASE [aifmda] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [aifmda] SET DB_CHAINING OFF 
GO

ALTER DATABASE [aifmda] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [aifmda] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [aifmda] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [aifmda] SET QUERY_STORE = OFF
GO

USE [aifmda]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [aifmda] SET  READ_WRITE 
GO


